"""empty message

Revision ID: 117e44e1508e
Revises: d51837bed15a
Create Date: 2023-03-07 21:19:22.081703

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '117e44e1508e'
down_revision = 'd51837bed15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('racks', schema='kijani_test')
    with op.batch_alter_table('trips', schema='kijani_test') as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='kijani_test') as batch_op:
        batch_op.drop_column('status')

    op.create_table('racks',
    sa.Column('id', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='racks_pkey'),
    schema='kijani_test'
    )
    # ### end Alembic commands ###
