"""empty message

Revision ID: bf5d7f9f5963
Revises: 
Create Date: 2023-03-01 10:11:01.072568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5d7f9f5963'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_station_rack_id', 'stations', type_='foreignkey')
    op.drop_column('stations', 'rack_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('rack_id', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_station_rack_id', 'stations', 'racks', ['rack_id'], ['id'])
    # ### end Alembic commands ###
