"""empty message

Revision ID: d3ebeaa7df14
Revises: 117e44e1508e
Create Date: 2023-03-08 19:50:53.525586

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd3ebeaa7df14'
down_revision = '117e44e1508e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema='kijani_test') as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'bike_types', ['type'], ['id'], referent_schema='kijani_test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema='kijani_test') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('type',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
