"""empty message

Revision ID: f9d0da54ad23
Revises: bf5d7f9f5963
Create Date: 2023-03-01 10:35:24.044185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d0da54ad23'
down_revision = 'bf5d7f9f5963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_rack_station_id', 'racks', type_='foreignkey')
    op.drop_column('racks', 'station_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racks', sa.Column('station_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_rack_station_id', 'racks', 'stations', ['station_id'], ['id'])
    # ### end Alembic commands ###
