"""empty message

Revision ID: 078430c3c785
Revises: d3ebeaa7df14
Create Date: 2023-03-08 20:02:43.998329

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '078430c3c785'
down_revision = 'd3ebeaa7df14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema='kijani_test') as batch_op:
        batch_op.drop_constraint('bikes_type_fkey', type_='foreignkey')
        batch_op.alter_column('type',
                new_column_name='type_id')
        batch_op.create_foreign_key('bikes_type_id_fkey', 'bike_types', ['type_id'], ['id'], referent_schema='kijani_test')
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema='kijani_test') as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bikes_type_fkey', 'bike_types', ['type'], ['id'], referent_schema='kijani_test')
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
